[package]
name = "git-prompt"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"

[dependencies]
git2 = { version = "0.8.0", default_features = false }
colorful = "0.2.1"
